packaging_format = 2

id = "cloudlog"
name = "Cloudlog"
description.en = "Web based amateur radio logging application"
description.fr = "Expliquez en *quelques* (10~15) mots l'utilité de l'app ou ce qu'elle fait (l'objectif est de donner une idée grossière pour des utilisateurs qui naviguent dans un catalogue de 100+ apps)"

version = "1.0~ynh1"

maintainers = ["johndoe"]

[upstream]
# NB: Only the "license" key is mandatory. Remove entries for which there's no relevant data
license = "MIT"
website = "https://www.cloudlog.co.uk"
demo = "https://demo.example.com"
admindoc = "https://yunohost.org/packaging_apps"
userdoc = "https://yunohost.org/apps"
code = "https://github.com/magicbug/Cloudlog"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = true
ldap = "?"
sso = "?"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/magicbug/Cloudlog/archive/refs/tags/2.4.3.tar.gz"
        sha256 = "82f23aba0ad3e1cadf62fd4d06ff6c82cae0c8adb470a24b0c7b3f0a6017894b"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "mariadb-server, php8.0-curl, php8.0-mbstring, php8.0-mysql, php8.0-xml, php8.0-openssl"

    [resources.database]
    type = "mysql"
